name = "FractionalDiffEq"
uuid = "c7492dd8-6170-483b-af64-cefb6c377d9a"
authors = ["Qingyu Qu"]
version = "0.1.0"

[deps]
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
InvertedIndices = "1.1"
SpecialFunctions = "1.8"
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
